 
services:
  postgres:
    image: 'postgres:16.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    networks:
      default:
        aliases:
          - postgres
  postgres2:
    image: 'postgres:16.2'
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: balancedb
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - ./db-data/postgres2/:/var/lib/postgresql/data/
    networks:
      default:
        aliases:
          - postgres
  kafka:
    image: 'apache/kafka:3.7.1'
    ports:
      - "9092:9092"
      - "9093:9093"
